#!/usr/bin/env bash
# Dependencies: iwconfig, siji

wifi=$(cat /sys/class/net/wlp*/operstate)
token="%{F<#icon_color#>}"

if [[ "$wifi" == "up" ]]; then
    ssid=$(iwgetid -r)
    if [[ $(nmcli con show --active | grep vpn) ]]; then
    	token="%{F<#vpn#>}  %{F-}"
	else 
    	token="%{F<#normal_color#>}  %{F-}"
    fi
else
    token="%{F<#network_down#>}  %{F-}"
    ssid="N/A"
fi

echo " $token$ssid "
