#!/usr/bin/env bash
# Dependencies: bspc, siji

bspc control --subscribe | while read -r line; do
    case $line in
        W*) window=""
            IFS=':'
            set -- ${line#?}
            while [[ $# -gt 0 ]]; do
                case $1 in
                    O*) window="${window}%{F#9BA59B}%{F-}"
                       ;;
                    F*) window="${window}%{F#9BA59B}%{F-}"
                        ;;
                    U*) window="${window}%{F#FB543F}%{F-}"
                        ;;
                    o*) window="${window}%{F#A89984}%{F-}"
                        ;;
                    f*) window="${window}%{F#A89984}%{F-}"
                        ;;
                    u*) window="${window}%{F#FB543F}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    echo "%{c}$window"
done
