#! /usr/bin/env bash
xmodmap ~/.Xmodmap

sxhkd &
urxvtd &

panel &

./bspwm_colors

compton -bcf -D 3
xsetroot -cursor_name left_ptr

bspc config border_width        5
bspc config window_gap         20

bspc config top_padding 30

bspc config ignore_ewmh_focus true
bspc config focus_follows_pointer true
bspc config pointer_follow_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI
