#! /usr/bin/env bash

xrdb -load ~/.Xresources

bspc config focused_border_color    "#c9b79f"
bspc config active_border_color     "#c9b79f"
bspc config presel_border_color     "#aa762d"
bspc config urgent_border_color     "#a95c33"
bspc config normal_border_color     "#1d2520"

hsetroot -fill ~/.config/bspwm/backgrounds/rustic.jpg
