#! /usr/bin/env bash
sxhkd &

polybar default -r &

# window aesthetics and panel padding
bspc config window_gap   18
bspc config top_padding  30
bspc config border_width  5

# monitor config
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

# focus
bspc config ignore_ewmh_focus      true
bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  true
bspc config pointer_follow_monitor true

# misc
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc rule -a Termite state=pseudo_tiled

# desktops
bspc monitor -d I II III IV V VI

bspwm_colors
