#! /usr/bin/env bash
sxhkd &

polybar default -r &

bspc config border_width 5
bspc config window_gap   16

bspc config top_padding    40
bspc config left_padding   10
bspc config right_padding  10
bspc config bottom_padding 10

bspc config ignore_ewmh_focus true

bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc config focus_follows_pointer  true
bspc config pointer_follow_monitor true
bspc config pointer_follows_focus  true

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI

bspwm_colors
