#! /usr/bin/env bash
xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap

sxhkd &
urxvtd &

panel &

compton -bcf -D 3
xsetroot -cursor_name left_ptr
hsetroot -fill ~/.config/bspwm/backgrounds/{{ background_file }}

bspc config border_width        5
bspc config window_gap         20

bspc config focused_border_color    "{{ colors.white }}"
bspc config active_border_color     "{{ colors.white }}"
bspc config presel_border_color     "{{ colors.yellow }}"
bspc config urgent_border_color     "{{ colors.red }}"
bspc config normal_border_color     "{{ colors.background }}"

bspc config top_padding 30

bspc config ignore_ewmh_focus true
bspc config focus_follows_pointer true
bspc config pointer_follow_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI
