#! /usr/bin/env bash

xrdb -load ~/.Xresources

bspc config focused_border_color    "{{ colors.white }}"
bspc config active_border_color     "{{ colors.white }}"
bspc config presel_border_color     "{{ colors.yellow }}"
bspc config urgent_border_color     "{{ colors.red }}"
bspc config normal_border_color     "{{ colors.background }}"

hsetroot -fill ~/.config/bspwm/backgrounds/{{ background_file }}
