#!/usr/bin/env bash
# Dependencies: acpi, siji

percentage1=$(cat /sys/class/power_supply/BAT0/capacity)
percentage2=$(cat /sys/class/power_supply/BAT1/capacity)
percentage=$(echo "scale=1; ($percentage1+$percentage2)/2" | bc -l)
low="{{ panel.battery.low }}"
med="{{ panel.battery.med }}"
high="{{ panel.battery.high }}"
token="-"

case $percentage in
    2[0-9]*)
        ;&
    3[0-9]*)
        ;&
    4[0-9]*)
       color=$med
       ;;
    5[0-9]*)
        ;&
    6[0-9]*)
        ;&
    7[0-9]*)
        ;&
    8[0-9]*)
        ;&
    9[0-9]*|10*)
       color=$high
       ;;
    1*)
        ;&
    *)
       color=$low
       ;;
esac

ac=$(cat /sys/class/power_supply/AC/online)

if [[ "$ac" == "1" ]]; then
    token="+"
fi

echo -e "%{B$color} $percentage%$token %{B-}"
