#!/usr/bin/env bash

focused="#8F4673"
urgent="#FB543F"

if ! type bspc &> /dev/null; then
	echo "bspc not found"
	exit 1
fi


while read -r line; do
	focus_desktops="%{B$focused}"
	urgent_desktops="%{B$urgent}"
	case $line in
		W*)
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ]; do
				item="$1"
				name="${item#?}"
				case $item in
					f*)
						# free desktop
						;&
					o*)
						# occupied desktop
						;;
					F*)
						# focused free desktop
						;&
					U*)
						# focused urgent desktop
						;&
					O*)
						# focused occupied desktop
						focus_desktops="$focus_desktops $name "
						;;
					u*)
						# urgent desktop
						urgent_desktops="$urgent_desktops $name "
						;;
				esac
				shift
			done
	esac
	echo -n "$urgent_desktops%{B-}$focus_desktops%{B-}"
	echo
done < <(bspc subscribe report)
