#!/usr/bin/env bash
volume=$(amixer sget Master | grep -m 1 -o '[0-9]\+%')
state=$(amixer sget Master | grep -m 1 -Eoe '\[(on|off)\]')

if [[ $state == '[off]' ]]; then
    volume="0%"
fi
echo "$volume"

while read -r line; do
    if [[ $(echo $line | grep ' sink ') ]]; then
        volume=$(amixer sget Master | grep -m 1 -o '[0-9]\+%')
        state=$(amixer sget Master | grep -m 1 -Eoe '\[(on|off)\]')

        if [[ $state == '[off]' ]]; then
            volume="0%"
        fi
        echo "$volume"
    fi
done< <(pactl subscribe)
